### ISSUE TITLE
Run RoCm docker images as unprivileged user

### ISSUE THREAD

**Issue by fxmarty** [RadeonOpenCompute/ROCm-docker#114]
Hi,

When developing, I tend to run my containers as non-root for convenience (notably, for shared files with the host). However, it appears that RoCm is then not well detected:

```
FROM rocm/dev-ubuntu-22.04:5.6.1

ARG DEBIAN_FRONTEND=noninteractive

# Run this container as unprivileged to avoid later issues with permissions on host.
ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    git \
    python3.10 \
    python3.10-dev \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 && \
    python -m pip install -U pip

RUN adduser user sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user
WORKDIR /home/user

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/test/rocm5.6/
```

Build with `docker build -f Dockerfile --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t my-dummy-container .`

And then 
```
docker run --pid host --device /dev/kfd --device /dev/dri -it --rm my-dummy-container:latest /bin/bash
python -c "import torch; torch.cuda.is_available()"
```

returns `False`, while it runs just fine (returns `True`) if I comment out `USER user`. What is funny is that `rocm-smi` runs fine both as root and unprivileged.

This issue does not arise with the [`nvidia/cuda`](https://hub.docker.com/r/nvidia/cuda) images on NVIDIA systems.

Is running as `root` a requirement? The documentation [mentions a non-root rocm-user](https://github.com/RadeonOpenCompute/ROCm-docker#rocm-user-has-root-privileges-by-default) but I can't find it using `awk -F: '$0=$1 " uid="$3' /etc/passwd`:

```
root uid=0
daemon uid=1
bin uid=2
sys uid=3
sync uid=4
games uid=5
man uid=6
lp uid=7
mail uid=8
news uid=9
uucp uid=10
proxy uid=13
www-data uid=33
backup uid=34
list uid=38
irc uid=39
gnats uid=41
nobody uid=65534
_apt uid=100
```

Thank you!

note: using `Docker version 24.0.6, build ed223bc`

**Comment by pruthvistony** [comment]
@fxmarty ,
Can you trying add your user ID to 'video' and 'render' groups on the host machine.

**Comment by fxmarty** [comment]
Thank you, adding the relevant usermod in the dockerfile works!
