### ISSUE TITLE
How to specify the devices

### ISSUE THREAD

**Issue by learner321** [RadeonOpenCompute/ROCm-docker#28]
I have one server that has two AMD gpus. When I use "--device=/dev/kfd ", all gpus can be seen in the containers. In my application, I want just one gpu can be seen in one container.  So I have a question that how to specify the device used in the container. 
Thank you very much~
:）

**Comment by kknox** [comment]
If you are writing at the HiP application layer, there are a few [environment variables](http://rocm-documentation.readthedocs.io/en/latest/Other_Solutions/Other-Solutions.html#hip-envorment-varibles) you can leverage to filter devices: **HIP_VISIBLE_DEVICES**

As far as I am aware, if you are writing code at a level below the HiP layer (like at the runtime or the hcc c++ ::hc layer), you will have to write code to enumerate and select the device yourself.
