### ISSUE TITLE
ROCm 1.7.0

### ISSUE THREAD

**Issue by VincentSC** [RadeonOpenCompute/ROCm-docker#30]
As ROCm 1.7.0 uses DKMS, the image needs to be pulled together differently. We bump into a "There is no device can be used to do the computation". The docker-instance is run as root, 1.6.4 worked fine and 1.7.0 works fine on the bare metal.

What are we missing?

**Comment by sunway513** [comment]
Hi @VincentSC , ROCm1.7 requires to add `--privileged` after `docker run` command, e.g.:
`sudo docker run -it -v $HOME:/data --privileged --device=/dev/kfd`
Could you try that?

**Comment by VincentSC** [comment]
That gets it to work indeed, but a privileged docker unfortunately is not an option due to security requirements. Can this also be solved by specifying the exact devices access is required to? Could you describe which access is blocked in a default unprivileged docker?

**Comment by kknox** [comment]
Hi @VincentSC 
I've been playing around with this myself.  Could you try something along the lines of:

docker run -it --rm --device /dev/kfd **--device /dev/dri/renderD128** rocm/dev-ubuntu-16.04 bash

You may need to replace the /dev/dri/renderD128 with whatever enumerates on your system.

**Comment by VincentSC** [comment]
Thanks! Not tried yet. But if that works, then the below script should theoretically work?
````
DRIDEVICES=""; for device in `find /dev/dri/ -iname "render*"`; do DRIDEVICES+=" --device ${device}"; done
# echo $DRIDEVICES
docker run -it --rm --device /dev/kfd $DRIDEVICES rocm/dev-ubuntu-16.04 bash
````

**Comment by kknox** [comment]
Let me know how that works out.  I think docker is going to require that --device flags must be absolute paths; looks like your script above is going to supply relative paths.  I'll try to confirm this works on my work machines on monday, and then update the documentation if so.

**Comment by VincentSC** [comment]
Both the script and your advice worked
````
$ DRIDEVICES=""; for device in `find /dev/dri/ -iname "render*"`; do DRIDEVICES+=" --device ${device}"; done; echo $DRIDEVICES
--device /dev/dri/renderD129 --device /dev/dri/renderD128
````
Now we can get back to work

**Comment by VincentSC** [comment]
This is still not solved in Docker. 

As a reference. When running docker from Gitlab CI, you need to add the DRI Devices to the gitlab-runner config:
```
[[runners]]
  name = "<name>"
  url = "<domain>"
  token = "<token>"
  executor = "docker"
  [runners.docker]
    image = "rocm/rocm-terminal:latest"
    privileged = false
    disable_cache = false
    devices = ["/dev/kfd", "/dev/dri"]
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
```

**Comment by VincentSC** [comment]
This is the config for Gitlab CI, that is in line with that. It says `privileged = false`.

**Comment by VincentSC** [comment]
You're misunderstanding. I put the solution as a reference. There is no problem!!

**Comment by sunway513** [comment]
Aha, thanks @VincentSC :-)
