### ISSUE TITLE
There is no device can be used to do the computation

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm-docker#32]
Trying to do anything gives me this error.

```
There is no device can be used to do the computation
```

System: debian 9
GPU: Vega 64 
Kernel: 4.9.0.5

already done a complete remove/reinstall of everything

**Comment by scchan** [comment]
maybe a permission issue, could you try adding the `--privileged` flag and see if that works??

**Comment by Dekken** [comment]
nope, will follow up @ https://github.com/ROCmSoftwarePlatform/hiptensorflow/issues/28
