### ISSUE TITLE
Which argument to docker should I use for having access to GPU through containers ?

### ISSUE THREAD

**Issue by Sumenia** [RadeonOpenCompute/ROCm-docker#39]
As of `rocm1.7.1`, which argument to docker should I use ?
` --privileged --device=/dev/kfd` as written in #30 ?
`--device /dev/kfd --device /dev/dri/renderD128` as @kknox answered in #30 ?
`--device=/dev/kfd --device=/dev/dri --group-add video` as written in `quick-start.md` ? ( I'm using this one)

`--device="/dev/kfd"` as written in the `README.md` doesn't work anymore with the last stable rocm, maybe we should update the doc accordingly ?

ps: none work without using sudo or being root user from inside the container as said in #36

**Comment by sunway513** [comment]
Hi @Sumenia, the thrid one is correct, and use the following is the minimum command to run rocm docker images:
`sudo docker run -it --device=/dev/kfd --device=/dev/dri --group-add video rocm/rocm-terminal`
I'll update the README.md, thanks for pointing it out. 
For docker launch without sudo access, please refer to my answers in the other [issue](https://github.com/RadeonOpenCompute/ROCm-docker/issues/36).
