### ISSUE TITLE
missing `sudo` in last verification line of Step 5 of Installation Instructions

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm-docker#40]
I needed to run `sudo ./vector_copy` for the sample to run.
The instructions only state `./vector_copy`

**Comment by sunway513** [comment]
`./vector_copy` is sufficient, please refer to the recommendation I just replied to your other issue.

**Comment by boxerab** [comment]
Thanks! That works. 

Some feedback : as a courtesy,it might be better to allow me to read your reply, test it for myself, and then close the issue myself. Of course if the issue remains open for a while, you could then close it yourself.

**Comment by sunway513** [comment]
Hi @boxerab , sorry if I close the issue too soon :-) 
This is a well-known issue. BTW, this recommendation has also been documented in the README.md.

**Comment by boxerab** [comment]
np. Thanks for your quick response.
