### ISSUE TITLE
Need to use sudo to run clinfo

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm-docker#41]
Is this normal? On bare metal install, using ubuntu packages, I don't need `sudo`

**Comment by sunway513** [comment]
The docker.ce release 18.02 has known defects working with rocm-user account insider docker image. Please upgrade docker package to the 18.04 build:
`https://download.docker.com/linux/ubuntu/dists/xenial/pool/nightly/amd64/docker-ce_18.04.0~ce~dev~git20180315.170650.0.8fabfd2-0~ubuntu_amd64.deb
`

**Comment by boxerab** [comment]
Thanks, that was the problem.
