### ISSUE TITLE
rocm-docker with kernel 4.17

### ISSUE THREAD

**Issue by stoneBricker** [RadeonOpenCompute/ROCm-docker#43]
Should rocm-docker work with a Fury X and kernel 4.17 on any distribution? Or do I still need to install rocm-dkms?

**Comment by sunway513** [comment]
Yes, rocm-dkms is still needed on kernel 4.17.
The 4.18 Linux kernel is the first Linux kernel where all the AMDGPU and KFD bit are upstreamed to support the ROCm userland.
