### ISSUE TITLE
i can't install compute-firmware 

### ISSUE THREAD

**Issue by nerolink** [RadeonOpenCompute/ROCm-docker#44]
i can't install compute-firmware use apt-get install compute-firmware

**Comment by sunway513** [comment]
Hi @nerolink , thanks for the heads up.
compute-firmware is currently integrated with rock-dkms, I've updated the document to remove it from the recommended installation list in this commit:
https://github.com/RadeonOpenCompute/ROCm-docker/commit/317356f9d64d6cf34c9500286bef830fc39fa9ad

**Comment by nerolink** [comment]
when i install rock-dkms i meet this problem.Can you help me?

>Need to get 0 B/5,279 kB of archives.
After this operation, 120 MB of additional disk space will be used.
(Reading database ... 215833 files and directories currently installed.)
Preparing to unpack .../rock-dkms_1.8-192_all.deb ...
Unpacking rock-dkms (1.8-192) ...
dpkg: error processing archive /var/cache/apt/archives/rock-dkms_1.8-192_all.deb (--unpack):
 trying to overwrite '/usr/share/dkms/modules_to_force_install/amdgpu', which is also in package amdgpu-dkms 18.30-641594
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/rock-dkms_1.8-192_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by fxkamd** [comment]
Looks like you already have amdgpu-dkms installed, which conflicts with rock-dkms.
