### ISSUE TITLE
path /opt/rocm/hsa/sample not exist in rocm-terminal image

### ISSUE THREAD

**Issue by aguegu** [RadeonOpenCompute/ROCm-docker#46]
I am following [the installation guide](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/quick-start.md) building the new `rocm-terminal` image. 

After step 4a, I got my container running, with `hcc --version` showing correct result. But the `sample` folder does not exist in `/opt/rocm/hsa/`, so I can not compile the sample code and run it

**Comment by qxzcode** [comment]
I'm having this same issue. From inside the docker container:

    ...$ ls -A /opt/rocm/hsa/
    LICENSE.txt  README.md  include  lib
    ...$ cd /opt/rocm/hsa/sample
    bash: cd: /opt/rocm/hsa/sample: No such file or directory

**Comment by sunway513** [comment]
Hi @aguegu @qxzcode thanks for the heads up, I've updated the document to suggest using rocminfo to verify installation status:
bf6f0db9bad3ada0fef774c9dc148ee183f4ce51

**Comment by zjunweihit** [comment]
Can we get the sample code from anywhere without ROCm installed?
That seems more general and convenient.

Regards,
Jerry

**Comment by atbraoy** [comment]
@sunway513, the command '/opt/rocm/bin/rocminfo' displays the available resource, it works well in pulling out all available 'Agents'. However, I think we still need the /opt/rocm/hsa/samples/ to demonstrate a successful completion/compilation of the ROCm environment/kernel. Samples/ contains vector-copy operation which is important. How can we get /samples/?

**Comment by sunway513** [comment]
Hi @atbraoy , the recent ROCm packages no longer provide hsa samples.
You can try the hip samples instead, e.g.
`/opt/rocm/hip/samples/1_Utils/hipBusBandwidth`

**Comment by atbraoy** [comment]
Thank @sunway513, appreciate your feedbck. I got it working and I can list all gpus in my machine from tensorflow as well as 'clinfo'. I wanted to run the benchmark because was planing to spin my own docker container, which is done now. I will start building models and give feedback as it goes.
Cheers.
