### ISSUE TITLE
Managing rocm and tensorflow-rocm versions

### ISSUE THREAD

**Issue by kostask777** [RadeonOpenCompute/ROCm-docker#70]
My question is not a specific issue with ROCm-docker but on it's capability to manage compatible versions between  ROCm and tensorflow-rocm. What I mean is that everything is fine (after some troubleshooting), if one's purpose is to install the latest tensorflow-rocm version on a compatible ROCm version (and in turn kernel version). But what happens when one wishes to run code of an older tensorflow version? How does the community resolve such situations? Can ROCm-docker help with this? Say be able to run ROCm 2.4 and tensorflow-rocm 1.13 without having to downgrade kernels?

Thank you

**Comment by sunway513** [comment]
Hi @kostask777 , you can refer to the following document to match ROCm versions and tensorflow-rocm PyPi whl package:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
