### ISSUE TITLE
rocm2.10.1-tf2.0-dev seems not work

### ISSUE THREAD

**Issue by SwordFaith** [RadeonOpenCompute/ROCm-docker#72]
I tried to use rocm2.10.1-tf2.0-dev docker in my legacy work. But when I run `apt update`, it shows bazel's GPG key expired. Then I tried to update the key follow bazel doc. After the key added, bazel ask `apt-transport-https` package as prequisite, which not include in the docker image. And there is not an index for `apt-transport-https`, so I have to run `apt update`. What a sadly dead-lock! Is there any way to walk-around, or dockerfile which allows me to build a new updated version with rocm2.10 and tf2.0.

**Comment by sunway513** [comment]
Hi @SwordFaith , that was a known issue, you can fix it with the following command:
```
rm /etc/apt/sources.list.d/rocm.list
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
apt update
```
